# Form implementation generated from reading ui file '_DeskTopEmbedded.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        Form.setStyleSheet("")
        self.avatar = QtWidgets.QLabel(parent=Form)
        self.avatar.setGeometry(QtCore.QRect(560, 440, 800, 450))
        self.avatar.setStyleSheet("background-color: white;")
        self.avatar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.avatar.setObjectName("avatar")
        self.bg_pic = QtWidgets.QWidget(parent=Form)
        self.bg_pic.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.bg_pic.setStyleSheet("background-image: url(\"./assets/happy.webp\");\n"
"background-repeat: no-repeat; \n"
"background-position: center;\n"
"background-attachment: fixed;\n"
"background-size: 100px 100px;")
        self.bg_pic.setObjectName("bg_pic")
        self.bg_pic.raise_()
        self.avatar.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.avatar.setText(_translate("Form", "TextLabel"))
