# Form implementation generated from reading ui file '_MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 614)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.prev = QtWidgets.QPushButton(parent=self.centralwidget)
        self.prev.setGeometry(QtCore.QRect(530, 40, 121, 51))
        self.prev.setObjectName("prev")
        self.embedded = QtWidgets.QPushButton(parent=self.centralwidget)
        self.embedded.setGeometry(QtCore.QRect(730, 120, 121, 51))
        self.embedded.setObjectName("embedded")
        self.nxt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.nxt.setGeometry(QtCore.QRect(530, 120, 121, 51))
        self.nxt.setObjectName("nxt")
        self.flush = QtWidgets.QPushButton(parent=self.centralwidget)
        self.flush.setGeometry(QtCore.QRect(530, 200, 121, 51))
        self.flush.setObjectName("flush")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 501, 571))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 21))
        self.menubar.setObjectName("menubar")
        self.menuconfig = QtWidgets.QMenu(parent=self.menubar)
        self.menuconfig.setObjectName("menuconfig")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionpeople = QtGui.QAction(parent=MainWindow)
        self.actionpeople.setObjectName("actionpeople")
        self.menuconfig.addAction(self.actionpeople)
        self.menubar.addAction(self.menuconfig.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.prev.setText(_translate("MainWindow", "前一个"))
        self.embedded.setText(_translate("MainWindow", "嵌入"))
        self.nxt.setText(_translate("MainWindow", "后一个"))
        self.flush.setText(_translate("MainWindow", "刷新"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "path"))
        self.menuconfig.setTitle(_translate("MainWindow", "config"))
        self.actionpeople.setText(_translate("MainWindow", "people"))
